#!/usr/bin/env bash
# Write backend.env.shared-qa for local Saleor using shared boto_qa credentials.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/backend.env.shared-qa"
BOTO_ENV="$ROOT/../saleor/deploy/.env.boto"
PROJECT="${GCP_PROJECT_ID:-feed-me-qa}"

read_env() {
  local file="$1" key="$2"
  grep -E "^${key}=" "$file" | head -1 | cut -d= -f2- | sed 's/^"//;s/"$//'
}

if [[ -f "$BOTO_ENV" ]]; then
  DB_URL="$(read_env "$BOTO_ENV" BOTO_DATABASE_URL)"
  CACHE_URL="$(read_env "$BOTO_ENV" BOTO_CACHE_URL)"
  BROKER_URL="$(read_env "$BOTO_ENV" BOTO_CELERY_BROKER_URL)"
  SECRET_KEY="$(read_env "$BOTO_ENV" BOTO_SECRET_KEY)"
elif command -v gcloud >/dev/null 2>&1; then
  DB_URL="$(gcloud secrets versions access latest --secret=boto-saleor-database-url --project="$PROJECT")"
  CACHE_URL="$(gcloud secrets versions access latest --secret=boto-saleor-cache-url --project="$PROJECT")"
  BROKER_URL="$(gcloud secrets versions access latest --secret=boto-saleor-celery-broker-url --project="$PROJECT")"
  SECRET_KEY="$(gcloud secrets versions access latest --secret=boto-saleor-secret-key --project="$PROJECT")"
else
  echo "Missing $BOTO_ENV and gcloud — copy backend.env.shared-qa.example to backend.env.shared-qa" >&2
  exit 1
fi

read -r DB_URL CACHE_URL BROKER_URL < <(python3 - "$DB_URL" "$CACHE_URL" "$BROKER_URL" <<'PY'
import sys
from urllib.parse import urlparse, urlunparse

def rewrite_db(url: str) -> str:
    normalized = url.replace("postgres://", "postgresql://", 1)
    parsed = urlparse(normalized)
    port = parsed.port or 5432
    netloc = f"{parsed.username}:{parsed.password}@host.docker.internal:{port}"
    return urlunparse(parsed._replace(scheme="postgresql", netloc=netloc))

def rewrite_redis(url: str) -> str:
    parsed = urlparse(url)
    port = parsed.port or 6379
    return urlunparse(parsed._replace(netloc=f"host.docker.internal:{port}"))

db, cache, broker = sys.argv[1:4]
print(rewrite_db(db), rewrite_redis(cache), rewrite_redis(broker))
PY
)

cat > "$OUT" <<EOF
# Generated by scripts/setup-shared-qa-env.sh — do not commit
DATABASE_URL=${DB_URL}
CACHE_URL=${CACHE_URL}
CELERY_BROKER_URL=${BROKER_URL}
SECRET_KEY=${SECRET_KEY}
DEFAULT_FROM_EMAIL=noreply@example.com
EMAIL_URL=smtp://mailpit:1025
OTEL_SERVICE_NAME=saleor
OTEL_TRACES_EXPORTER=otlp
OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
EOF

echo "Wrote $OUT"
echo "Next:"
echo "  ./scripts/shared-qa-tunnel.sh start"
echo "  make up-shared"
